name=str("30")
age=int(22)
height=float(5.9)
print("My name is" , name,"I am",age,"years old" "my height is" ,height,)
print(type(name),type(age),type(height) )
name1=int(name)
print("converted:",name1, type(name1))
height1=int(height)
print("converted:",height1, type(height1))